openapi: 3.0.3
info:
  title: DACNPM
  version: 1.0.0
servers:
  - url: http://localhost:80/api
tags:
  - name: authen-author
    description: API authen author
  - name: printer
    description: API printer
  - name: print-order
    description: API print order
  - name: account
    description: API account
paths:
  /auth/signin:
    post:
      tags:
        - authen-author
      summary: sign in account
      operationId: login
      requestBody:
        description: Sign in info
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: khang@hcmut.edu.vn
                password:
                  type: string
                  example: 123456
        required: true
      responses:
        '200':
          description: Login successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  full_name:
                    type: string
                    example: Tống Duy Khang
                  number_page:
                    type: integer
                    example: 30
                  last_login:
                    type: string
                    example: 2024-11-16T03:03:56.316Z
                  access_token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MzAxMzUzNDI4MWMwOWY5M2Q3ZWZkYyIsImlhdCI6MTczMTcyNjIzNiwiZXhwIjoxNzMxODEyNjM2fQ.botg4HW1kba8R7Spg9QPJMFDaDs1vSShRm_UZ0dDX1E
        '404':
          description: user not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User not found!

  /auth/signout:
    post:
      tags:
        - authen-author
      summary: sign out account
      operationId: logout
      responses:
        default:
          description: Logout successfully
  
  /test/client:
    get:
      tags:
        - authen-author
      summary: author client
      operationId: client
      responses:
        '200':
          description: access client board successfully
          content:
            application/json:
              schema:
                type: string
                example: client content!!!!
        '403':
          description: Forbidden - different scenarios
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                noTokenProvide:
                  summary: chưa signin
                  value:
                    message: no token provide
                notRole:
                  summary: không phải role client
                  value:
                    message: Require client role!
  
  /test/admin:
    get:
      tags:
        - authen-author
      summary: author admin
      description: tương tự với client
      operationId: admin
      responses:
        '200':
          description: access admin board successfully
          content:
            application/json:
              schema:
                type: string
                example: admin content!!!!

  /printers:
    get:
      tags:
        - printer
      summary: get all printer (printer, Lich su in SPSO)
      responses:
        default:
          description: get successfull
          content: 
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  brand:
                    type: string
                  machine_model:
                    type: string
                  state:
                    type: boolean
                  campus:
                    type: string
                  building:
                    type: string
                  room:
                    type: string

    post:
      tags:
        - printer
      summary: add printer
      requestBody:
        description: Sign in info
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                brand:
                  type: string
                machine_model:
                  type: string
                state:
                  type: boolean
                campus:
                  type: string
                building:
                  type: string
                room:
                  type: string
        required: true
      responses:
        '200':
          description: Add successfully

  /printers/{id}:
    delete:
      tags:
        - printer
      summary: delete printer
      responses:
        default:
          description: delete successfully
    
    put:
      tags:
        - printer
      summary: update state
      requestBody:
        description: state of printer
        content:
          application/json:
            schema:
              type: object
              properties:
                state:
                  type: boolean
      responses:
        default:
          description: update successfull
          content: 
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  brand:
                    type: string
                  machine_model:
                    type: string
                  state:
                    type: boolean
                  campus:
                    type: string
                  building:
                    type: string
                  room:
                    type: string

  /printOrders:
    post:
      tags:
        - print-order
      summary: add print order
      requestBody:
        description: print order info
        content:
          application/json:
            schema:
              type: object
              properties:
                page_size:
                  type: string
                page_orientation:
                  type: string
                sided:
                  type: string
                pages_to_printed:
                  type: number
                pages_per_sheet:
                  type: number
                number_of_copies:
                  type: number 
                total_print_pages:
                 type: number
                file_id:
                  type: string
                printer_id:
                  type: string
        required: true
      responses:
        '200':
          description: Add successfully

    get: 
      tags:
        - print-order
      summary: get all print order (Lich su in SPSO)
      responses:
        '200':
          description: get Print Order successfully
          content: 
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  client_id:
                    type: string
                  printer_id:
                    type: string
                  file_id:
                    type: string
                  page_size:
                    type: string
                  page_orientation:
                    type: string
                  state:
                    type: string
                  scale:
                    type: number
                  pages_to_printed:
                    type: string
                  pages_per_sheet:
                    type: string
                  total_print_pages:
                    type: string
                  isTransaction:
                    type: boolean

    
  


  /printOrders/my:
    get:
      tags:
        - print-order
      summary: get Order by client 
      requestBody:
        description: get all Order by client
        content:
          application/json:
            schema:
              type: object
              properties:
                client_id:
                  type: string
        required: true
      responses:
        '200':
          description: get Print Order successfully
          content: 
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  client_id:
                    type: string
                  printer_id:
                    type: string
                  file_id:
                    type: string
                  page_size:
                    type: string
                  page_orientation:
                    type: string
                  state:
                    type: string
                  scale:
                    type: number
                  pages_to_printed:
                    type: string
                  pages_per_sheet:
                    type: string
                  total_print_pages:
                    type: string
                  isTransaction:
                    type: boolean

  /printOrders/confirm:
    patch:
      tags:
      - print-order
      summary: Confirm Print Order
    
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                _id:
                  type: string
        required: true
      responses:
        '200':
          description: Confirm Print Order successfully
          content: 
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  client_id:
                    type: string
                  printer_id:
                    type: string
                  file_id:
                    type: string
                  page_size:
                    type: string
                  page_orientation:
                    type: string
                  state:
                    type: string
                  scale:
                    type: number
                  pages_to_printed:
                    type: string
                  pages_per_sheet:
                    type: string
                  total_print_pages:
                    type: string
                  isTransaction:
                    type: boolean

  /printOrders/:id/update:
    put:
      tags:
      - print-order
      summary: Update Print Order
    
      requestBody:
        content:  
          application/json: 
            schema:
              type: object
              properties:
                printer_id:
                  type: string
                page_size:
                  type: string
                page_orientation:
                  type: string
                sided:
                  type: string
                pages_per_sheet:
                  type: string
                number_of_copies:
                  type: string
        required: true
      responses:
        200:
          description: Update Print Order successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  client_id:
                    type: string
                  printer_id:
                    type: string
                  file_id:
                    type: string
                  page_size:
                    type: string
                  page_orientation:
                    type: string
                  state:
                    type: string
                  scale:
                    type: number
                  pages_to_printed:
                    type: string
                  pages_per_sheet:
                    type: string
                  total_print_pages:
                    type: string
                  isTransaction:
                    type: boolean

  /printOrders/filterSPSO:
    get:
      tags:
        - print-order
      summary: filter (Lich su in SPSO)
      parameters:
        - in: query
          name: client_id
          schema:
            type: string
          required: false
          description: filter by client_id
        - in: query
          name: printer_id
          schema:
            type: string
          required: false
          description: filter by printer_id
        - in: query
          name: startDate
          schema:
            type: string
          required: false
          description: filter by state
        - in: query
          name: endDate
          schema:
            type: string
          required: false
          description: filter by state
      responses:
        '200':
          description: filter successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  client_id:
                    type: string
                  printer_id:
                    type: string
                  file_id:
                    type: string
                  page_size:
                    type: string
                  page_orientation:
                    type: string
                  state:
                    type: string
                  scale:
                    type: number
                  pages_to_printed:
                    type: string
                  pages_per_sheet:
                    type: string
                  total_print_pages:
                    type: string
                  isTransaction:
                    type: boolean

  /account/updatePage:
    put:
      tags:
        - account
      summary: update number of page (Printing)
      requestBody:
        description: update number of page
        content:
          application/json:
            schema:
              type: object
              properties:
                total_print_pages:
                  type: number
        required: true
      responses:
        '200':
          description: update successfully

  /account/allClient:
    get:
      tags:
        - account
      summary: get all client (Lich su in SPSO)
      responses:
        '200':
          description: get all client successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  full_name:
                    type: string
                  number_page:
                    type: number
                  last_login:
                    type: string
          
  
   



      
  



  





          
